### ISSUE TITLE
failed to get the version of the plugin sdk: failed to find the version of the plugin sdk

### ISSUE THREAD

**Issue by WangXiaoJin** [langgenius/dify-plugin-daemon#284]
when I install myself plugin by local package.  The `dify-plugin-daemon` container print the error 'failed to find the version of the plugin sdk'. But the plugin is running normally.

```
2025/05/14 13:59:34 environment_python.go:334: [ERROR]failed to get the version of the plugin sdk: failed to find the version of the plugin sdk
```

requirements.txt:
```
dify_plugin>=0.1.0,<0.2.0
```

manifest.yaml:
```
version: 0.0.3
type: plugin
.......
meta:
  version: 0.0.1
  arch:
    - amd64
    - arm64
  runner:
    language: python
    version: "3.12"
    entrypoint: main
  minimum_dify_version: 1.1.0
created_at: 2025-05-08T11:27:56.2403359+08:00
privacy: PRIVACY.md
verified: false

```
